<?php 

class enlineamixmodmotherhoodaward2021ModuleFrontController extends ModuleFrontController
{
	public function __construct()
	{
		parent::__construct();
		$this->context = Context::getContext();
	}
	
	public function init()
    {
        parent::init();
    }
	
	public function initContent()
    {
        parent::initContent();
		$this->context->controller->addJS('themes/default-bootstrap/dashboard-assets/readmore-js/readmore.min.js');
		$arr_category = array(
			"Pregnant",
			"Pregnant",
			"Pregnant",
			"Pregnant",
			"Pregnant",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Newborn",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Toddler",
			"Family",
			"Family",
			"Family",
			"Family",
			"Family",
		);
		
		$arr_brandname = array(
			"BabyLove",
			"Cryocord",
			"Lifree",
			"Nestle",
			"Sofy",
			"Akarana Baby",
			"B&B",
			"B&B",
			"BabyLove",
			"Baby Love",
			"BabyOrganix",
			"BabyOrganix",
			"Bubbles",
			"Bubbles",
			"Fiffy",
			"Kath+Belle",
			"MamyPoko",
			"Philips Avent",
			"Ezbaby",
			"Nuby",
			"Mombella",
			"Philips Avent",
			"Shapee",
			"Philips Avent",
			"MamyPoko",
			"TrendyValley",
			"BabyLove",
			"Simple Dimple",
			"BabyLove",
			"Nestle",
			"Coby",
			"Fiffy",
			"Cody Haus",
			"Koopers",
			"Poppy",
			"Novamil",
			"Sweet Heart Paris",
			"Nestle",
			"Nuby",
			"Taf Toys",
			"GB Pockit+",
			"Philips Avent",
			"Cheekaaboo",
			"Philips Avent",
			"Lolly Gummy",
			"Nestle",
			"Philips Avent",
			"Simple Dimple",
			"Bubbles",
			"B&B",
			"BabyOrganix",
			"BabyOrganix",
			"BabyOrganix",
			"B&B",
		);
		
		$arr_productname = array(
			"BabyLove Gift Hamper",
			"Cryocord Stemcell Bank",
			"Lifree Powerful Slim Pants",
			"Nestle Mom & Me",
			"Sofy Body Fit Nite ",
			"Akarana Tuhinga Organic Baby Lounger",
			"B&B Tooth Tissues",
			"B&B Laundry Soap",
			"Babylove Anti-Slip Bath Mat",
			"Babylove Organic Bean Sprout Husk Pillow",
			"Baby Feeding Bottle Wash",
			"BabyOrganix Nature’s First Aid Cream",
			"Bubbles 3 IN 1 BABY WALKER",
			"Bubbles STEAM & DRY STERILIZER",
			"FIFFY Baby Laundry Detergent",
			"Kath + Belle BunnySmile Baby 1st Tooth Gel ",
			"MamyPoko Gentle Cleansing Wipes",
			"Philips Avent Berry Soother Night Time",
			"Ez Baby Ergonomic Hipseat",
			"Nuby Soft Air Silicone Feeding Bottle",
			"Mombella Teethers ",
			"Philips Avent Essential Baby Food Maker",
			"Shapee Sassy Nursing Bra",
			"Philips Avent Newborn Starter Set",
			"MamyPoko Air Fit",
			"Trendyvalley Organic Cotton Baby Romper",
			"BabyLove Premium Nursing Pillow",
			"Simple Dimple X Hipster Keepster Papa Shield Bag",
			"Babylove 4 in 1 Foam Mattress Set + Pillow and Bolsters",
			"Nestle Lactogrow",
			"Coby UV Sterilizer Version 2.0",
			"FIFFY Vest Suits",
			"Coby Haus: Safety Play Fence",
			"Koopers Co-Rider",
			"Poppy Seat High Chair Cover",
			"Novamil Kid IT",
			"Sweet Heart Paris CS287Car Seat",
			"Nestle Nankid Optipro HA",
			"Nuby 360 Wonder Cup",
			"Taf Toys Developmental Cube",
			"GERMANY gb Pockit Plus ",
			"Philips Avent Thermal Bottle Warmer",
			"Cheekaaboo Warmiebabes Thermal Swimsuit",
			"Philips Avent 3-in-1 Electric Steam Sterilizer",
			"Lolly Gummy 3 in 1 Slide Swing Indoor Playground",
			"Nestle Cerelac Infant Cereals With Milk Brown Rice and Milk",
			"Philips Avent Easy Comfort Single Electric Breast Pump",
			"Simple Dimple Unicorn Friends Activity Playgym With Cute Pillow",
			"Bubbles THERMAL SENSOR DOUBLE ZIPLOCK BREASTMILK BAGS",
			"B&B Safe Disinfectant Wet Tissue",
			"BabyOrganix Baby Bottom Soothing Cream",
			"Babyorganix O'Clean Liquid Laundry Detergent",
			"BabyOrganix Naturally Kinder Sanitising Water",
			"B&B Korea No.1 Skin Protection",
		);
		
		$arr_awardname = array(
			"Best Gift Hamper",
			"Best Stem Cell Bank",
			"Best Adult Disposable Diaper",
			"Best Mom Nutrition",
			"Best Feminine Pad",
			"Best Organic Lounger",
			"Best Baby Tooth Tissue",
			"Best Maternity & Newborn Laundry Soap",
			"Best Baby Bath Accessories",
			"Best Beansprout Pillow",
			"Best Bottle Wash",
			"Best Eczema Baby Range",
			"Best Baby Walker",
			"Best Steam & Dry Sterilizer",
			"Best Plant Based Baby Laundry Detergent",
			"Best Baby Tooth Gel",
			"Best Baby Wipes",
			"Best Night Soother",
			"Best Ergonomic Hipseat Carrier",
			"Best Baby Silicone Bottle",
			"Best Baby Teether Toys",
			"Best Baby Food Maker",
			"Best Nursing Bra & Disposable Pad",
			"Best Best Newborn Set",
			"Best Baby Disposable Diaper",
			"Best Organic Cotton Baby Clothing",
			"Best Nursing Pillow",
			"Best Baby Diaper Bag",
			"Best Bedding & Nursery",
			"Best Comfort Growing Up Milk",
			"Best UV Starilizer",
			"Best Comfortable Eyelet Vest Suits",
			"Best Safety Play Fence & Playmat",
			"Best 3-IN-1 Co-Rider",
			"Best Baby Seat Cover",
			"Best Kids Growing Up Milk",
			"Best Car Seat",
			"Best Partially Hydrolysed Protein Milk",
			"Best 360 Wonder Cup",
			"Best Developmental Toys",
			"Best Cabin Size Stroller",
			"Best Thermal & Electric Bottle Warmer",
			"Best Thermal Swimsuit",
			"Best Electric Steam Sterilizer",
			"Best Indoor PlayGround",
			"Best Toddler Weaning Nutrition",
			"Best BreastPump & Accessories",
			"Best Baby Activity PlayGym",
			"Best Double Ziplock Breastmilk Bags",
			"Best Disinfectant Wet Wipes",
			"Best Baby Diaper Cream",
			"Best Family Laundry Detergent",
			"Best Natural Sanitising Water",
			"Best Skin Laundry Proctection",
		);
		
		$arr_purchaselink = array(
			"NA",
			"NA",
			"NA",
			"https://www.motherhood.com.my/NestleStartWell/baby-food/mummy-food/mummy-supplements/nestle-mom-me-vanilla-pregnant-lactating-milk-350g.html",
			"NA",
			"https://www.motherhood.com.my/harenet-marketing/nursery/baby-kids-bedding/baby-mattresses/akarana-tuhinga-organic-baby-lounger.html",
			"NA",
			"NA",
			"https://www.motherhood.com.my/babylove/baby-bathing/bath-accessories/bath-tubs-support-mats/babylove-anti-slip-bath-mat.html",
			"https://www.motherhood.com.my/babylove/nursery/baby-kids-bedding/baby-blankets-pillows/babylove-organic-pillow-sprout-captain-blue.html",
			"https://www.motherhood.com.my/kath-belle/health-safety/household/bottle-accessories-cleaner/babyorganix-feeding-bottle-wash-800ml.html",
			"https://www.motherhood.com.my/kath-belle/baby-bathing/baby-care/baby-cream/babyorganix-nature-s-first-aid-cream-30gm.html",
			"https://www.motherhood.com.my/grato-marketing-sdn-bhd/baby-gears/other-gears/baby-walkers/bubbles-3-in-1-baby-walker-galaxy.html",
			"https://www.motherhood.com.my/grato-marketing-sdn-bhd/baby-feeding/bottle-feeding/baby-bottle-sterilizer/bubbles-steam-dry-sterilizer.html?search_query=Bubbles+STEAM+%26+DRY+STERILIZER&results=2",
			"https://www.motherhood.com.my/fiffy/health-safety/household/baby-laundry-cleaners/fiffy-baby-laundry-detergent-2537-2000ml-20490460.html",
			"NA",
			"NA",
			"https://www.motherhood.com.my/philips-avent/baby-feeding/toddler-feeding/baby-pacifiers-teethers/philips-avent-berry-soother-night-time-0-6m-boy-twin-pack-bearstars.html",
			"https://www.motherhood.com.my/super-store-marketing/baby-gears/other-gears/baby-carriers-slings/ez-baby-ergonomic-hipseat-urban-comfort-skyblue.html",
			"NA",
			"NA",
			"NA",
			"https://www.motherhood.com.my/shapee/baby-clothing/maternity-wear/nursing-bras-panties/shapee-sassy-nursing-bra-black.html",
			"https://www.motherhood.com.my/philips-avent/baby-feeding/bottle-feeding/baby-bottles-teats/philips-avent-newborn-starter-set-natural-20-softer-teats.html",
			"https://www.motherhood.com.my/little-sasa/diapers/baby-diapers/disposable-diapers/mamypoko-airfit-girl-pants-9-14kg-l44-x-4.html?search_query=MamyPoko+&results=9",
			"https://www.motherhood.com.my/trendyvalley-collections/baby-clothing/baby-wear/baby-rompers/trendyvalley-organic-cotton-baby-romper-little-singer.html",
			"https://www.motherhood.com.my/babylove/baby-feeding/breast-feeding/nursing-pillow/babylove-nursing-pillow-jumbo-joy.html?gclid=Cj0KCQjw5auGBhDEARIsAFyNm9Elr_oMk8FZJct5jjyG1DFkWoKKhDyOd3RTLaduQXWjlcnjzxGfllYaArwhEALw_wcB",
			"https://www.motherhood.com.my/retro-baby/diapers/diapering-accessories/diaper-bags/simple-dimple-x-hipster-keepster-papa-shield-bag-xl-black.html",
			"https://www.motherhood.com.my/babylove/nursery/baby-kids-bedding/kids-bedroom-set/babylove-4-in-1-foam-mattress-set-pillow-bolsters-animal-stars.html",
			"https://www.motherhood.com.my/NestleStartWell/baby-food/organic-baby-food/baby-formula/nestle-lactogrow-3-milk-powder-13kg-twin-pack.html",
			"https://www.motherhood.com.my/my-lovely-baby/baby-feeding/bottle-feeding/baby-bottle-sterilizer/coby-haus-uv-20-sterilizer.html",
			"NA",
			"NA",
			"https://www.motherhood.com.my/little-kids-nest/baby-gears/stroller/light-weight-stroller/koopers-co-rider-black.html?search_query=Koopers&results=6",
			"https://www.motherhood.com.my/poppy-junior/baby-gears/other-gears/baby-gear-accessories/poppy-seat-high-chair-cover-blue-owl.html",
			"https://www.motherhood.com.my/delfi-marketing-sdn-bhd/baby-food/organic-baby-food/toddler-formula/toddlerhood/novamil-kid-it-growing-up-formula-800g-1-10-years.html",
			"https://www.motherhood.com.my/iguana-online/baby-gears/car-seat/infant-car-seats/sweet-heart-paris-cs287-group-012-car-seat-black-grey-with-shock-absorption.html",
			"https://www.motherhood.com.my/NestleStartWell/baby-food/organic-baby-food/toddler-formula/toddlerhood/nestle-nankid-optipro-ha-3-1-years-above-800g-exp-date-20022022.html",
			"NA",
			"NA",
			"https://www.motherhood.com.my/iguana-online/baby-gears/stroller/light-weight-stroller/gb-pockit-plus-all-terrain-rose-red-world-lightweight-cabin-size-stroller-with-reclining-seat-official-store-2019.html",
			"https://www.motherhood.com.my/littledinoshop/baby-feeding/bottle-feeding/baby-bottle-warmer/philips-avent-thermal-bottle-warmer.html",
			"https://www.motherhood.com.my/cheekaaboo/baby-clothing/baby-wear/baby-swim-wear/cheekaaboo-warmiebabes-thermal-swimsuit-surfer-summer-paradise.html",
			"https://www.motherhood.com.my/philips-avent/baby-feeding/bottle-feeding/baby-bottle-sterilizer/philips-avent-sterilizer-dryer.html",
			"NA",
			"https://www.motherhood.com.my/NestleStartWell/baby-food/organic-baby-food/baby-cereal-puffs/weaning/nestle-cerelac-porridge-chkn-100g.html",
			"https://www.motherhood.com.my/philips-avent/baby-feeding/breast-feeding/breast-pump/philips-avent-easy-comfort-single-electric-breast-pump.html",
			"NA",
			"https://www.motherhood.com.my/grato-marketing-sdn-bhd/baby-feeding/breast-feeding/breast-milk-storage-bags-accessories/bubbles-thermal-sensor-double-ziplock-breastmilk-bags-34oz-25pcs-x-4pcs.html?search_query=Bubbles+THERMAL+SENSOR+DOUBLE+ZIPLOCK+BREASTMILK+BAGS&results=3",
			"NA",
			"https://www.motherhood.com.my/kath-belle/baby-bathing/baby-care/baby-lotion-oil/babyorganix-bottom-soothing-cream-50gm.htmll",
			"https://www.motherhood.com.my/kath-belle/health-safety/household/baby-laundry-cleaners/babyorganix-o-clean-liquid-laundry-detergent-1l.html",
			"https://www.motherhood.com.my/kath-belle/baby-bathing/baby-care/baby-grooming/pre-order-babyorganix-naturally-kinder-sanitising-water-400ml.html",
			"NA",
		);
		
		$arr_storylink = array(
			"NA",
			"https://story.motherhood.com.my/blog/10-things-to-know-about-cryocord/",
			"NA",
			"",
			"NA",
			"NA",
			"NA",
			"NA",
			"NA ",
			"https://story.motherhood.com.my/blog/mum-approved-tips-to-help-your-baby-sleep-through-the-night/",
			"",
			"",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-bubbles-steam-dry-sterilizer/",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-bubbles-steam-dry-sterilizer/",
			"NA",
			"",
			"NA",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"NA",
			"NA",
			"NA",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"NA",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"NA",
			"NA",
			"https://story.motherhood.com.my/blog/benefits-of-using-a-nursing-pillow/",
			"NA",
			"NA",
			"https://story.motherhood.com.my/blog/new-nestle-lactogrow-aktif-formulated-with-more-calcium/",
			"",
			"NA",
			"NA",
			"NA",
			"https://story.motherhood.com.my/blog/recipients-motherhood-choice-awards-2019/",
			"NA",
			"https://story.motherhood.com.my/blog/baby-car-seat-ultimate-guide-2020/",
			"NA",
			"NA",
			"NA",
			"NA",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"NA",
			"https://story.motherhood.com.my/blog/new-cerelac-citarasa-ibu-for-toddlers/",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-philips-avent-newborn-starter-set/",
			"NA",
			"https://story.motherhood.com.my/blog/motherhood-choice-awards-2019-top-3-most-voted-winner-bubbles-steam-dry-sterilizer/",
			"NA",
			"NA",
			"NA",
			"NA",
			"NA",
		);
		
		$arr_imglink = array(
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/pregnant/pregnant-1.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/pregnant/pregnant-2.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/pregnant/pregnant-3.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/pregnant/pregnant-4.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/pregnant/pregnant-5.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-1.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-2.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-3.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-4.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-5.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-7.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-8.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-9.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-10.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-12.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-13.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-14.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-18.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-11.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-17.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-16.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-19.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-21.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-20.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-15.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-23.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-24.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-22.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/newborn/newborn-6.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-10.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-4.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-5.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-3.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-7.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-15.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-19.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-17.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-10-1.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-11.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-18.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-6.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-14.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-2.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-13.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-8.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-9.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-12.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-16.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/toddler/toddler-1.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/family/family-1.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/family/family-2.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/family/family-3.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/family/family-4.png",
			"https://s3.amazonaws.com/motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Products/family/family-5.png",
		);
		
		$arr_productlist = array();
		
		foreach($arr_category as $indx => $category)
		{
			$arrcategory['brandname'] 	  = (isset($arr_brandname[$indx]) && strtolower($arr_brandname[$indx]) != 'na') ? $arr_brandname[$indx]  : '';
			$arrcategory['productname']  = (isset($arr_productname[$indx]) && strtolower($arr_productname[$indx]) != 'na') ? $arr_productname[$indx]  : '';
			$arrcategory['awardname'] 	  = (isset($arr_awardname[$indx]) && strtolower($arr_awardname[$indx]) != 'na') ? $arr_awardname[$indx]  : '';
			$arrcategory['purchaselink'] = (isset($arr_purchaselink[$indx]) && strtolower($arr_purchaselink[$indx]) != 'na') ? $arr_purchaselink[$indx]  : '';
			$arrcategory['storylink'] 	  = (isset($arr_storylink[$indx]) && strtolower($arr_storylink[$indx]) != 'na') ? $arr_storylink[$indx]  : '';
			$arrcategory['imagelink'] 	  = (isset($arr_imglink[$indx]) && strtolower($arr_imglink[$indx]) != 'na') ? $arr_imglink[$indx]  : '';
			$arr_productlist[strtolower($category)][] = $arrcategory;
		}
		
		

        $photogallery = array( "IMG_2767.jpg","IMG_2769.jpg","IMG_2771.jpg","IMG_2772.jpg","IMG_2846.jpg","IMG_2847.jpg","IMG_2849.jpg","IMG_2852.jpg","IMG_2853.jpg",
                        "IMG_2856.jpg","IMG_2858.jpg","IMG_2860.jpg","IMG_2861.jpg","IMG_2864.jpg","IMG_2866.jpg","IMG_2868.jpg","IMG_2871.jpg","IMG_2874.jpg",
                        "IMG_2877.jpg","IMG_2881.jpg","IMG_2883.jpg","IMG_2884.jpg","IMG_2887.jpg","IMG_2889.jpg","IMG_2891.jpg","IMG_2893.jpg","IMG_2896.jpg",
                        "IMG_2899.jpg","IMG_2901.jpg","IMG_2902.jpg","IMG_2905.jpg","IMG_2908.jpg","IMG_2909.jpg","IMG_2911.jpg","IMG_2913.jpg","IMG_2915.jpg",
                        "IMG_2916.jpg","IMG_2919.jpg","IMG_2921.jpg","IMG_2923.jpg","IMG_2924.jpg","IMG_2926.jpg","IMG_2939.jpg","IMG_2942.jpg","IMG_2943.jpg",
                        "IMG_2944.jpg","IMG_2945.jpg","IMG_2949.jpg","IMG_2951.jpg","IMG_2955.jpg","IMG_2958.jpg","IMG_2964.jpg","IMG_2968.jpg","IMG_2970.jpg",
                        "IMG_3093.jpg","IMG_8397.jpg","IMG_8398.jpg","IMG_8401.jpg","IMG_8403.jpg","IMG_8405.jpg","IMG_8427.jpg","IMG_8437.jpg","IMG_8438.jpg",
                        "IMG_8440.jpg","IMG_8441.jpg","IMG_8442.jpg","IMG_8444.jpg","IMG_8452.jpg","IMG_8453.jpg","IMG_8454.jpg","IMG_19238.jpeg");
        $this->context->smarty->assign(array(
            'photogallery' => $photogallery,
            'arr_productlist' => $arr_productlist,
        ));
        
        $this->context->smarty->tpl_vars['meta_title']->value = "Motherhood Choice Awards 2021 | Motherhood.com.my Malaysia";
        $this->context->smarty->tpl_vars['meta_image']->value = "https://cdn.motherhood.com.my/assets/images/uploads/2021/Motherhood+Choice+Awards+2021/Secondpage/banner-2ndpage.png";
        $this->context->smarty->tpl_vars['meta_description']->value = "best brands & products in baby feeding, gears, diaper, enrichment, feminine care, health & safety, mom kids nutrition, maternity & nursing, household & more";
            
        $this->setTemplate('motherhoodaward2021.tpl');
    }

    public function postProcess(){
        if (Tools::isSubmit('submit')){
        }
		return parent::postProcess();
    }
}